version: "3.0"

services:
  api:
    build: ./
    depends_on:
      - db
    ports:
      - "3001:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/clinica_veterinaria
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  db:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinica_veterinaria
      MYSQL_USER: developer
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./db-volume:/var/lib/mysql
